-- P1 API/webhooks: complete the webhook backend with real signed delivery.
-- Existing (unchanged): api_key_create/verify/revoke (complete), webhook_register/delete/enqueue +
-- webhook_endpoints(secret auto-generated by column default) + webhook_deliveries(status/attempts/
-- next_attempt_at backoff schema). Missing pieces added here: (1) reveal/rotate the per-endpoint signing
-- secret, (2) an actual delivery worker that POSTs via pg_net with an HMAC-SHA256 signature + capped
-- exponential-backoff retries, scheduled on pg_cron.
--
-- Prereq: webhook_deliveries.status check must allow 'dispatched' and 'retrying'
--   (see 20260710_p1_webhook_deliveries_status_expand.sql).
--
-- Signature scheme (Stripe-style): signed = "<unix_ts>.<compact-json-body>"; sig = HMAC_SHA256(signed, secret);
--   header  X-Avertyn-Signature: t=<ts>,v1=<hex>   (also X-Avertyn-Event, X-Avertyn-Delivery).
--   Receiver reconstructs "<t>." + <raw request body> and recomputes the HMAC with its endpoint secret.
--
-- Verified on demo: registered an endpoint → webhook_send_test → webhook_deliver_pending dispatched it
-- (attempts=1, request_id set, signature set); example.com returned 405 → webhook_reconcile set
-- status='retrying', response_code=405, backoff scheduled; stored signature recomputes == true. Test rows removed.

ALTER TABLE public.webhook_deliveries ADD COLUMN IF NOT EXISTS request_id    bigint;
ALTER TABLE public.webhook_deliveries ADD COLUMN IF NOT EXISTS response_code integer;
ALTER TABLE public.webhook_deliveries ADD COLUMN IF NOT EXISTS signature     text;

CREATE OR REPLACE FUNCTION public.webhook_secret(p_id uuid)
 RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $function$
  select secret from public.webhook_endpoints
  where id = p_id and (public.auth_org_id() is null or org_id = public.auth_org_id());
$function$;

CREATE OR REPLACE FUNCTION public.webhook_rotate_secret(p_id uuid)
 RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','extensions'
AS $function$
declare v text;
begin
  update public.webhook_endpoints set secret = encode(gen_random_bytes(24),'hex')
   where id = p_id and (public.auth_org_id() is null or org_id = public.auth_org_id())
   returning secret into v;
  if v is null then raise exception 'endpoint not found or not authorized'; end if;
  return v;
end $function$;

CREATE OR REPLACE FUNCTION public.webhook_send_test(p_id uuid)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
declare e record; did bigint;
begin
  select * into e from public.webhook_endpoints
   where id = p_id and (public.auth_org_id() is null or org_id = public.auth_org_id());
  if not found then return jsonb_build_object('ok',false,'reason','not_found'); end if;
  insert into public.webhook_deliveries(org_id, endpoint_id, event, payload)
    values(e.org_id, e.id, 'ping',
           jsonb_build_object('type','ping','ts',extract(epoch from now())::bigint,'message','Avertyn webhook test'))
    returning id into did;
  return jsonb_build_object('ok',true,'delivery',did,'note','queued; the worker delivers within ~1 minute');
end $function$;

-- Phase 1 — dispatch due deliveries via pg_net with an HMAC signature header.
CREATE OR REPLACE FUNCTION public.webhook_deliver_pending(p_limit int DEFAULT 100)
 RETURNS int LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','extensions'
AS $function$
declare r record; ts bigint; sig text; req bigint; n int := 0;
begin
  for r in
    select d.id, d.event, d.payload, e.url, e.secret
    from public.webhook_deliveries d
    join public.webhook_endpoints e on e.id = d.endpoint_id
    where d.status in ('pending','retrying') and d.next_attempt_at <= now() and e.active
    order by d.next_attempt_at
    limit p_limit
  loop
    ts  := extract(epoch from now())::bigint;
    sig := encode(extensions.hmac(ts::text || '.' || r.payload::text, r.secret, 'sha256'),'hex');
    req := net.http_post(
      url := r.url,
      body := r.payload,
      headers := jsonb_build_object(
        'Content-Type','application/json',
        'X-Avertyn-Event', r.event,
        'X-Avertyn-Delivery', r.id::text,
        'X-Avertyn-Signature', 't=' || ts::text || ',v1=' || sig),
      timeout_milliseconds := 5000);
    update public.webhook_deliveries
      set status='dispatched', attempts = attempts + 1, request_id = req,
          signature = 't=' || ts::text || ',v1=' || sig,
          next_attempt_at = now() + interval '2 minutes'   -- guard: reconcile timeout if no response lands
      where id = r.id;
    n := n + 1;
  end loop;
  return n;
end $function$;

-- Phase 2 — fold pg_net responses back into delivery status with capped exponential backoff (max 8 attempts).
CREATE OR REPLACE FUNCTION public.webhook_reconcile(p_limit int DEFAULT 200)
 RETURNS int LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','extensions'
AS $function$
declare r record; resp record; n int := 0; wait interval;
begin
  for r in
    select id, request_id, attempts, next_attempt_at
    from public.webhook_deliveries
    where status='dispatched' and request_id is not null
    order by next_attempt_at
    limit p_limit
  loop
    wait := case when r.attempts <= 1 then interval '1 minute'
                 when r.attempts = 2 then interval '5 minutes'
                 when r.attempts = 3 then interval '15 minutes'
                 when r.attempts = 4 then interval '1 hour'
                 when r.attempts = 5 then interval '3 hours'
                 else interval '6 hours' end;
    select status_code, error_msg, timed_out into resp from net._http_response where id = r.request_id;
    if not found then
      if r.next_attempt_at <= now() then
        if r.attempts >= 8 then
          update public.webhook_deliveries set status='failed', last_error='timeout (no response)' where id=r.id;
        else
          update public.webhook_deliveries set status='retrying', next_attempt_at=now()+wait,
            last_error='pending-response timeout' where id=r.id;
        end if;
        n := n + 1;
      end if;
      continue;
    end if;
    if resp.status_code between 200 and 299 then
      update public.webhook_deliveries set status='delivered', response_code=resp.status_code,
        delivered_at=now(), last_error=null where id=r.id;
    elsif r.attempts >= 8 then
      update public.webhook_deliveries set status='failed', response_code=resp.status_code,
        last_error=coalesce(resp.error_msg, 'http '||coalesce(resp.status_code::text,'error')) where id=r.id;
    else
      update public.webhook_deliveries set status='retrying', response_code=resp.status_code,
        next_attempt_at=now()+wait,
        last_error=coalesce(resp.error_msg, 'http '||coalesce(resp.status_code::text,'error')) where id=r.id;
    end if;
    n := n + 1;
  end loop;
  return n;
end $function$;

-- Cross-org workers: cron/service only, never anon/authenticated.
REVOKE EXECUTE ON FUNCTION public.webhook_deliver_pending(int) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.webhook_reconcile(int)       FROM anon, authenticated;

-- Schedule the worker on pg_cron (every minute). Guard against duplicate job names.
DO $$ begin perform cron.unschedule('avertyn-webhook-deliver');   exception when others then null; end $$;
DO $$ begin perform cron.unschedule('avertyn-webhook-reconcile'); exception when others then null; end $$;
SELECT cron.schedule('avertyn-webhook-deliver',   '* * * * *', $job$ select public.webhook_deliver_pending(200); $job$);
SELECT cron.schedule('avertyn-webhook-reconcile', '* * * * *', $job$ select public.webhook_reconcile(500); $job$);
